// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Product.Service.Infrastructure.Data.EntityFramework;

#nullable disable

namespace Product.Service.Infrastructure.Data.EntityFramework.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250516080118_initDataAdd")]
    partial class initDataAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Product.Service.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lightweight running shoes with cushioned sole",
                            Name = "Running Shoes",
                            Price = 89.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Waterproof hiking boots for rough terrain",
                            Name = "Hiking Boots",
                            Price = 129.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Comfortable everyday sneakers",
                            Name = "Casual Sneakers",
                            Price = 69.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "High-top basketball shoes with ankle support",
                            Name = "Basketball Shoes",
                            Price = 119.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Elegant leather dress shoes for formal occasions",
                            Name = "Formal Dress Shoes",
                            Price = 149.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Comfortable summer sandals",
                            Name = "Sandals",
                            Price = 39.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Professional soccer cleats for optimal performance",
                            Name = "Soccer Cleats",
                            Price = 109.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Insulated winter boots for cold weather",
                            Name = "Winter Boots",
                            Price = 89.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Easy slip-on loafers for casual wear",
                            Name = "Slip-on Loafers",
                            Price = 59.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Specialized shoes for tennis courts",
                            Name = "Tennis Shoes",
                            Price = 74.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Cotton crew neck t-shirt",
                            Name = "T-Shirt",
                            Price = 19.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Classic denim jeans with straight fit",
                            Name = "Jeans",
                            Price = 49.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Warm hoodie with front pocket",
                            Name = "Hoodie",
                            Price = 39.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Insulated winter jacket for extreme cold",
                            Name = "Winter Jacket",
                            Price = 129.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Two-piece formal suit for business occasions",
                            Name = "Formal Suit",
                            Price = 199.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            Description = "Button-up dress shirt for formal wear",
                            Name = "Dress Shirt",
                            Price = 45.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "Casual summer shorts",
                            Name = "Shorts",
                            Price = 29.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Warm knit sweater for winter",
                            Name = "Sweater",
                            Price = 54.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Quick-dry material swimwear",
                            Name = "Swimsuit",
                            Price = 34.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "Comfortable sleepwear set",
                            Name = "Pajamas",
                            Price = 24.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "Latest model smartphone with high-resolution camera",
                            Name = "Smartphone",
                            Price = 899.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "Lightweight laptop with high-performance processor",
                            Name = "Laptop",
                            Price = 1299.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 23,
                            Description = "10-inch tablet with retina display",
                            Name = "Tablet",
                            Price = 499.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 24,
                            Description = "Noise-cancelling wireless earbuds",
                            Name = "Wireless Earbuds",
                            Price = 149.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 25,
                            Description = "Fitness tracking smartwatch with heart rate monitor",
                            Name = "Smart Watch",
                            Price = 249.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 26,
                            Description = "Next-gen gaming console with 1TB storage",
                            Name = "Gaming Console",
                            Price = 499.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 27,
                            Description = "Professional DSLR camera with 24MP sensor",
                            Name = "Digital Camera",
                            Price = 799.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 28,
                            Description = "Portable waterproof bluetooth speaker",
                            Name = "Bluetooth Speaker",
                            Price = 79.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 29,
                            Description = "E-ink display e-reader with backlight",
                            Name = "E-reader",
                            Price = 129.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 30,
                            Description = "2TB portable external hard drive",
                            Name = "External Hard Drive",
                            Price = 89.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 31,
                            Description = "Programmable coffee maker with thermal carafe",
                            Name = "Coffee Maker",
                            Price = 79.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 32,
                            Description = "High-speed blender for smoothies and soups",
                            Name = "Blender",
                            Price = 69.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 33,
                            Description = "4-slice toaster with multiple settings",
                            Name = "Toaster",
                            Price = 49.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 34,
                            Description = "10-piece non-stick cookware set",
                            Name = "Cookware Set",
                            Price = 149.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 35,
                            Description = "Professional 8-piece knife set with block",
                            Name = "Knife Set",
                            Price = 99.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 36,
                            Description = "Cordless stick vacuum with HEPA filter",
                            Name = "Vacuum Cleaner",
                            Price = 199.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 37,
                            Description = "6-person wooden dining table",
                            Name = "Dining Table",
                            Price = 299.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 38,
                            Description = "3-seater fabric sofa with chaise",
                            Name = "Sofa",
                            Price = 599.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 39,
                            Description = "Queen size wooden bed frame",
                            Name = "Bed Frame",
                            Price = 249.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 40,
                            Description = "Adjustable LED desk lamp with USB port",
                            Name = "Desk Lamp",
                            Price = 39.99m,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 41,
                            Description = "Latest fiction bestseller novel",
                            Name = "Fiction Bestseller",
                            Price = 24.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 42,
                            Description = "International cuisine cookbook with 500 recipes",
                            Name = "Cookbook",
                            Price = 29.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 43,
                            Description = "Popular self-improvement book",
                            Name = "Self-Help Book",
                            Price = 19.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 44,
                            Description = "Comprehensive world history book",
                            Name = "History Book",
                            Price = 34.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 45,
                            Description = "Award-winning sci-fi novel",
                            Name = "Science Fiction Novel",
                            Price = 22.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 46,
                            Description = "Biography of influential historical figure",
                            Name = "Biography",
                            Price = 27.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 47,
                            Description = "Illustrated children's story book",
                            Name = "Children's Book",
                            Price = 14.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 48,
                            Description = "Comprehensive travel guide with maps",
                            Name = "Travel Guide",
                            Price = 21.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 49,
                            Description = "Beginner's guide to programming",
                            Name = "Programming Book",
                            Price = 39.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 50,
                            Description = "Coffee table art book with high-quality prints",
                            Name = "Art Book",
                            Price = 49.99m,
                            ProductTypeId = 5
                        },
                        new
                        {
                            Id = 51,
                            Description = "Non-slip exercise yoga mat",
                            Name = "Yoga Mat",
                            Price = 29.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 52,
                            Description = "Professional tennis racket with case",
                            Name = "Tennis Racket",
                            Price = 89.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 53,
                            Description = "Official size indoor/outdoor basketball",
                            Name = "Basketball",
                            Price = 24.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 54,
                            Description = "4-person waterproof camping tent",
                            Name = "Camping Tent",
                            Price = 129.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 55,
                            Description = "50L hiking backpack with hydration system",
                            Name = "Hiking Backpack",
                            Price = 79.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 56,
                            Description = "Mountain bike with 21 speeds",
                            Name = "Bicycle",
                            Price = 349.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 57,
                            Description = "Complete set of golf clubs for beginners",
                            Name = "Golf Clubs Set",
                            Price = 299.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 58,
                            Description = "Telescopic fishing rod with reel",
                            Name = "Fishing Rod",
                            Price = 59.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 59,
                            Description = "Pair of 5kg adjustable dumbbells",
                            Name = "Dumbbells",
                            Price = 49.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 60,
                            Description = "Anti-fog ski goggles with UV protection",
                            Name = "Ski Goggles",
                            Price = 39.99m,
                            ProductTypeId = 6
                        },
                        new
                        {
                            Id = 61,
                            Description = "Gentle facial cleanser for all skin types",
                            Name = "Facial Cleanser",
                            Price = 14.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 62,
                            Description = "Moisturizing shampoo for dry hair",
                            Name = "Shampoo",
                            Price = 12.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 63,
                            Description = "Luxury perfume with floral notes",
                            Name = "Perfume",
                            Price = 79.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 64,
                            Description = "Rechargeable electric razor for men",
                            Name = "Electric Razor",
                            Price = 89.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 65,
                            Description = "Professional hair dryer with diffuser",
                            Name = "Hair Dryer",
                            Price = 59.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 66,
                            Description = "Complete makeup kit with 30 colors",
                            Name = "Makeup Kit",
                            Price = 49.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 67,
                            Description = "Daily face moisturizer with SPF 30",
                            Name = "Moisturizer",
                            Price = 19.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 68,
                            Description = "10-piece nail polish set with various colors",
                            Name = "Nail Polish Set",
                            Price = 29.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 69,
                            Description = "Sonic electric toothbrush with timer",
                            Name = "Electric Toothbrush",
                            Price = 69.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 70,
                            Description = "Hydrating sheet face masks, pack of 10",
                            Name = "Face Mask",
                            Price = 24.99m,
                            ProductTypeId = 7
                        },
                        new
                        {
                            Id = 71,
                            Description = "Creative building blocks set, 500 pieces",
                            Name = "Building Blocks",
                            Price = 39.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 72,
                            Description = "Family strategy board game",
                            Name = "Board Game",
                            Price = 29.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 73,
                            Description = "High-speed remote control race car",
                            Name = "Remote Control Car",
                            Price = 49.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 74,
                            Description = "Soft plush teddy bear, 18 inches",
                            Name = "Stuffed Animal",
                            Price = 19.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 75,
                            Description = "Collectible superhero action figure",
                            Name = "Action Figure",
                            Price = 24.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 76,
                            Description = "1000-piece landscape jigsaw puzzle",
                            Name = "Puzzle",
                            Price = 17.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 77,
                            Description = "Family card game for 2-6 players",
                            Name = "Card Game",
                            Price = 12.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 78,
                            Description = "STEM learning toy for ages 8-12",
                            Name = "Educational Toy",
                            Price = 34.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 79,
                            Description = "Beginner drone with HD camera",
                            Name = "Drone",
                            Price = 89.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 80,
                            Description = "Wooden doll house with furniture",
                            Name = "Doll House",
                            Price = 69.99m,
                            ProductTypeId = 8
                        },
                        new
                        {
                            Id = 81,
                            Description = "Premium single-origin coffee beans, 1lb",
                            Name = "Gourmet Coffee",
                            Price = 18.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 82,
                            Description = "Assorted gourmet chocolates, 24 pieces",
                            Name = "Chocolate Box",
                            Price = 29.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 83,
                            Description = "Organic herbal tea assortment, 40 bags",
                            Name = "Organic Tea",
                            Price = 14.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 84,
                            Description = "Artisanal Italian pasta varieties, 5 pack",
                            Name = "Pasta Set",
                            Price = 22.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 85,
                            Description = "Extra virgin olive oil, 500ml",
                            Name = "Olive Oil",
                            Price = 19.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 86,
                            Description = "Gourmet spice collection, 12 jars",
                            Name = "Spice Collection",
                            Price = 39.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 87,
                            Description = "Premium red wine, vintage 2018",
                            Name = "Wine Bottle",
                            Price = 49.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 88,
                            Description = "Assorted fruit jam set, 4 jars",
                            Name = "Jam Set",
                            Price = 24.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 89,
                            Description = "Gourmet cheese assortment, 5 types",
                            Name = "Cheese Selection",
                            Price = 34.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 90,
                            Description = "High-protein snack bars, box of 12",
                            Name = "Protein Bars",
                            Price = 19.99m,
                            ProductTypeId = 9
                        },
                        new
                        {
                            Id = 91,
                            Description = "Premium ruled notebook, 200 pages",
                            Name = "Notebook",
                            Price = 12.99m,
                            ProductTypeId = 10
                        },
                        new
                        {
                            Id = 92,
                            Description = "Luxury ballpoint pen set, 5 pens",
                            Name = "Pen Set",
                            Price = 29.99m,
                            ProductTypeId = 10
                        },
                        new
                        {
                            Id = 93,
                            Description = "Ergonomic office chair with lumbar support",
                            Name = "Office Chair",
                            Price = 199.99m,
                            ProductTypeId = 10
                        },
                        new
                        {
                            Id = 94,
                            Description = "Multi-compartment desk organizer",
                            Name = "Desk Organizer",
                            Price = 24.99m,
                            ProductTypeId = 10
                        },
                        new
                        {
                            Id = 95,
                            Description = "Wireless all-in-one color printer",
                            Name = "Printer",
                            Price = 159.99m,
                            ProductTypeId = 10
                        },
                        new
                        {
                            Id = 96,
                            Description = "Cross-cut paper shredder for home office",
                            Name = "Paper Shredder",
                            Price = 49.99m,
                            ProductTypeId = 10
                        },
                        new
                        {
                            Id = 97,
                            Description = "2-drawer metal filing cabinet",
                            Name = "Filing Cabinet",
                            Price = 79.99m,
                            ProductTypeId = 10
                        },
                        new
                        {
                            Id = 98,
                            Description = "Wall-mounted magnetic whiteboard, 36x24\"",
                            Name = "Whiteboard",
                            Price = 39.99m,
                            ProductTypeId = 10
                        },
                        new
                        {
                            Id = 99,
                            Description = "Scientific calculator with 417 functions",
                            Name = "Calculator",
                            Price = 19.99m,
                            ProductTypeId = 10
                        },
                        new
                        {
                            Id = 100,
                            Description = "Heavy-duty stapler with 5000 staples",
                            Name = "Stapler",
                            Price = 14.99m,
                            ProductTypeId = 10
                        });
                });

            modelBuilder.Entity("Product.Service.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Shoes"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Books"
                        },
                        new
                        {
                            Id = 6,
                            Type = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 7,
                            Type = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 8,
                            Type = "Toys & Games"
                        },
                        new
                        {
                            Id = 9,
                            Type = "Food & Beverage"
                        },
                        new
                        {
                            Id = 10,
                            Type = "Office Products"
                        });
                });

            modelBuilder.Entity("Product.Service.Models.Product", b =>
                {
                    b.HasOne("Product.Service.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
