services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # environment:
    # - RABBITMQ_DEFAULT_USER=user
    # - RABBITMQ_DEFAULT_PASS=user
    networks:
      - app-network
  # postgresql:
  #   container_name: postgresql_msa
  #   image: postgres:latest
  #   ports:
  #     - "15432:15432"
  #   environment:
  #     - "POSTGRES_USER=postgres"
  #     - "POSTGRES_PASSWORD=parktest1#"
  #   networks:
  #     - app-network
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  product:
    depends_on:
        #- postgresql
        - rabbitmq
        - redis
    container_name: product  
    build: 
        context: .
        dockerfile: ./product-microservice/Product.Service/Dockerfile
    ports:
        - "8002:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMq__HostName=host.docker.internal:5672
        - ConnectionStrings__Default=Server=shpark94.synology.me;Database=Product;Port=25432;User Id=postgres;Password=parktest1#;
        # - "RabbitMq__UserName=guest"
        # - "RabbitMq__Password=guest"
  basket:
    container_name: basket
    depends_on:
      - redis
      - rabbitmq
    build:
      context: .
      dockerfile: ./basket-microservice/Basket.Service/Dockerfile
    ports:
      - "8000:8080"
    environment:
      - "RabbitMq__HostName=host.docker.internal:5672"
      - "Redis__Configuration=host.docker.internal:6379"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.58
    ports:
      - "4317:4317"
      - "16686:16686"
    networks:
      - app-network
  networks:
    app-network:
      driver: bridge