services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # environment:
    # - RABBITMQ_DEFAULT_USER=user
    # - RABBITMQ_DEFAULT_PASS=user
    networks:
    - app-network
  # postgresql:
  #   container_name: postgresql_msa
  #   image: postgres:latest
  #   ports:
  #     - "15432:15432"
  #   environment:
  #     - "POSTGRES_USER=postgres"
  #     - "POSTGRES_PASSWORD=parktest1#"
  #   networks:
  #     - app-network
  product:
    depends_on:
        #- postgresql
        - rabbitmq
    container_name: product  
    build: 
        context: .
        dockerfile: ./product-microservice/Product.Service/Dockerfile
    ports:
        - "8002:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMq__HostName=host.docker.internal
        - ConnectionStrings__Default=Server=shpark94.synology.me;Database=Product;Port=25432;User Id=postgres;Password=parktest1#;
        # - "RabbitMq__UserName=guest"
        # - "RabbitMq__Password=guest"
#     networks:
#       - app-network
# networks:
#   app-network:
#     driver: bridge